require 'rake/clean'

task :default => "Zmq.dll"

file "Zmq.dll" => "Zmq.cs" do
  sh "csc /nologo /target:library Zmq.cs"
end
CLOBBER.add("Zmq.dll")

file "Client.exe" => ["Zmq.dll", "Client.cs"] do |t|
  sh "csc /nologo /r:Zmq.dll Client.cs"
end
CLOBBER.add("Client.exe")

task :test => "Client.exe" do
  ENV["PATH"] += ";..\\..\\lib"
  sh "Client.exe"
end
